name: Pre-commit Checks

on:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python for GitHub Action
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for GitHub Action
        run: |
          pip install pylint pycodestyle bandit pytest pytest-custom_exit_code

      - name: Passes PyTest tests
        run: |
          pytest --suppress-no-test-exit-code .

      - name: Linting checks
        run: |
          repo_name="$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)"
          pylint --disable=E0401 "$repo_name"
      
      - name: Code style checks
        run: |
          repo_name="$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)"
          pycodestyle "$repo_name"

      - name: Security checks
        run: |
          repo_name="$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)"
          bandit "$repo_name"
